[tool.poetry]
name = "db_connector"
version = "0.1.0"
description = "Conector genérico de bases de datos"
authors = ["Tu Nombre <tu@correo.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
